# for debugging
management:
  endpoints:
    web:
      exposure:
        include: "*"
# for local MCP Inspector
mcp:
  local:
    cors:
      allowed-origin: "http://localhost:6274"
      allowed-methods: GET, POST, OPTIONS
      allowed-headers: "*"
      allow-credentials: true
logging:
  level:
    com.aloievets.ai.mcp.kafka: debug
